Support for detaching prepared XA transactions
codership/wsrep-lib pull request #126
Opened 2020-03-25 14:49 UTC by sciascid

Add support for detaching XA transactions. This is useful for handling
the case where the DBMS client has a transaction in prepared state and
disconnects. Before disconnect, the DBMS calls the newly introduced
client_state::xa_detach(), to cleanup the local transaction and
convert it to a high priority transaction. The DBMS may later attempt
to terminate the transaction through client_state::commit_by_xid() or
client_state::rollback_by_xid().

2020-09-28 13:26 UTC, temeo requested changes

2020-09-28 13:26 UTC, temeo commented on include/wsrep/client_service.hpp
> +        /*
Please use the same comment format as elsewhere in this file.

2020-09-28 13:26 UTC, temeo commented on include/wsrep/xid.hpp
> +        xid(long format_id, long gtrid_len,
Maximum values for `gtrid_len` and `bqual_len` are 64. Maybe this should be at least asserted in this constructor.

2020-10-28 10:01 UTC, temeo approved these changes

2020-10-28 13:41 UTC, sciascid commented on src/transaction.cpp
> +            assert(state() == s_prepared);
fixed

2020-10-28 13:42 UTC, sciascid commented on include/wsrep/client_state.hpp
> +        void xa_detach()
fixed

2020-11-09 07:25 UTC, temeo approved these changes

2020-11-09 14:14 UTC, merged